# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/text_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/text_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/text_service.proto\x12\x0btextservice\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"&\n\x0cTextResponse\x12\x16\n\x0eprocessed_text\x18\x01 \x01(\t2S\n\x0bTextService\x12\x44\n\x0bProcessText\x12\x18.textservice.TextRequest\x1a\x19.textservice.TextResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.text_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTREQUEST']._serialized_start=41
  _globals['_TEXTREQUEST']._serialized_end=68
  _globals['_TEXTRESPONSE']._serialized_start=70
  _globals['_TEXTRESPONSE']._serialized_end=108
  _globals['_TEXTSERVICE']._serialized_start=110
  _globals['_TEXTSERVICE']._serialized_end=193
# @@protoc_insertion_point(module_scope)
